MODEL:

TRAIN:
  train_data_dir: [
    './dataset/mydata/train1',
    './dataset/mydata/train2',
  ]
  cdistnet:
    dst_vocab: 'cdistnet/utils/dict_36.txt'   
    dst_vocab_size: 40
    rgb2gray: False
    keep_aspect_ratio: False
    width: 128 #100
    height: 32 #32
    max_width: 180
    is_lower: True 
    cnn_num: 2
    leakyRelu: False
    hidden_units: 512
    ff_units: 1024      #ff
    scale_embedding: True
    attention_dropout_rate: 0.0
    residual_dropout_rate: 0.1
    num_encoder_blocks: 3
    num_decoder_blocks: 3
    num_heads: 8
    beam_size: 10
    n_best: 1
    data_aug: True
    num_fiducial: 20           #number of fiducial points of TPS-STN
    train_method: 'origin'     #dist:  use distributed train method origin
    optim: 'origin'
    # method choice
    tps_block: 'TPS'      # TPS None
    feature_block: 'Resnet45'  # Resnet45 Resnet31 MTB
    test:
      device: 'cuda'

  batch_size: 10
  width: 128
  height: 32
  epochs: 50000
  cuda: True
  ngpu: 4
  workers: 8
  resume: ''
  ckpt_dir: './ckpt/'
  voc_type: 'all'
  saveInterval: 200
  displayInterval: 50
  adadelta: False
  lr: 0.0001
  adam: True
  beta1: 0.5
  manualSeed: 1234
  max_len: 100
  keep_ratio: False
  down_sample_scale: 2

  VAL:
    val_data_dir: [
      './dataset/mydata/test/easy',
      './dataset/mydata/test/medium',
      './dataset/mydata/test/hard',
    ]
    n_vis: 10
    vis_dir: 'demo'
    valInterval: 1000
    rec_pretrained: 'None'
    moran_pretrained: 'None'
    crnn_pretrained: './dataset/mydata/crnn.pth'

TEST:
  checkpoint: ''
  test_data_dir: [
  ]

CONVERT:
  image_dir:
  lmdb_dir:
  n_convert: 10
